name: "Runner Telemetry Action"
description: "Collect system telemetry from GitHub Actions runners with visual dashboards and per-step tracking."
author: "tsviz"
inputs:
  enabled:
    description: "Enable or disable telemetry. Set to 'false' to skip collection without removing from workflow."
    required: false
    default: "true"
  mode:
    description: "Operation mode: 'start' begins collection, 'stop' ends and generates report, 'step' marks a boundary, 'snapshot' for quick capture."
    required: false
    default: "start"
  interval:
    description: "Sampling interval in seconds for metrics collection."
    required: false
    default: "2"
  step-name:
    description: "Name of the current step (used with mode: 'step' to mark step boundaries for per-step analysis)."
    required: false
    default: ""
  repo-visibility:
    description: "Repository visibility: 'public' (standard runners are free), 'private' (standard runners cost money), or 'auto' (auto-detect from GitHub context). Affects cost analysis and billing context in reports."
    required: false
    default: "auto"
outputs:
  report-path:
    description: "Path to the generated markdown telemetry report"
  dashboard-path:
    description: "Path to the interactive HTML dashboard"
  data-path:
    description: "Path to the raw telemetry data JSON"
  csv-path:
    description: "Path to the time-series CSV file"
  summary-path:
    description: "Path to the dashboard-ready summary JSON"
  enabled:
    description: "Whether telemetry was enabled for this run"
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/post.js"
  post-if: "always()"
branding:
  icon: "activity"
  color: "blue"
